#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap -layout gb &
nitrogen --restore &
picom &
thunar --daemon &
dunst &
~/.config/polybar/launch.sh
killall "nm-applet"
nm-applet &
killall "volumeicon"
volumeicon &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs desktop='^8' state=floating follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a Shortwave desktop='^9' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
